### ISSUE TITLE
Kubernetes 1.23+ does not mount service account token anymore

### ISSUE THREAD

**Issue by gugu** [IBM/core-dump-handler#140]
Now in addition to providing AWS Role ARN chart needs to create service account token. Example:
```
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: core-dump-sa
  creationTimestamp: "2023-03-22T19:14:32Z"
  name: core-dump-token-secret
  namespace: monitoring
type: kubernetes.io/service-account-token
```
