### ISSUE TITLE
tolerations are falsely defined as an object instead of an array

### ISSUE THREAD

**Issue by Semmix** [IBM/core-dump-handler#62]
tolerations are falsely defined as an object instead of an array in the schema.json file
Had to delete the schema.json to get this to work

**Comment by No9** [comment]
Hey @Semmix 
Thanks for your interest in the project.
It looks like we inherited this from the helm template generator as we took the defaults from there.
Anyway would you be able to provide a toleration definition that illustrates what you are trying to achieve?
I can add that to the [CI tests](https://github.com/IBM/core-dump-handler/tree/main/charts/core-dump-handler/ci ) and get a fix out that solves your case.

**Comment by Semmix** [comment]
If i try to set tolerations the following way:
```
tolerations:
  - effect: NoSchedule
    key: stage
    operator: Equal
    value: component
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: stage
              operator: In
              values:
                - component
```
I get this error: 

```
Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
core-dump-handler:
- tolerations: Invalid type. Expected: object, given: array
```

if I try and set it as an object:
```
tolerations:
    effect: NoSchedule
    key: stage
    operator: Equal
    value: component
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: stage
              operator: In
              values:
                - component
```
i get the following error : 

```
error validating "": error validating data: ValidationError(DaemonSet.spec.template.spec.tolerations): invalid type for io.k8s.api.core.v1.PodSpec.tolerations: got "map", expected "array"`
```
